version: '3'

services:
  kurento:
    image: preinstalled-curento-media-server:latest
    ports:
      - "${KURENTO_PORT}:8888"
    volumes:
      - ${KURENTO_MOUNT_VOLUME_PATH}:/recorders

  db:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER_PASSWORD}
      TZ: ${MYSQL_TIME_ZONE}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: