version: '3'

services:
  kurento:
    image: preinstalled-curento-media-server:latest
    ports:
      - "172.16.201.44:${KURENTO_PORT}:8888/tcp"
      - "5000-5300:5000-5300/tcp"
    volumes:
      - ${KURENTO_MOUNT_VOLUME_PATH}:/recorders
    environment:
      KMS_EXTERNAL_IPV4: "172.16.201.44"
      KMS_MIN_PORT: 5000
      KMS_MAX_PORT: 5300
      KMS_ICE_TCP: 1

  db:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER_PASSWORD}
      TZ: ${MYSQL_TIME_ZONE}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: